# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/python/black
    rev: 24.10.0
    hooks:
    -   id: black
        exclude: "^(pixem/resources_rc.py)"
        args: [--line-length, '100']
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    hooks:
    -   id: clang-format
        exclude: "^(design/|pixel/|setup.py$|pixem/resources_rc.py)"
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.6
    hooks:
    # Run the linter.
    -   id: ruff
        types_or: [ python, pyi ]
        args: [--line-length, '100', --fix, --exit-non-zero-on-fix]
        exclude: "^(design/|pixel/|setup.py$|pixem/resources_rc.py)"
